const FALLBACK_SITE={brand:'NINELIJ',pageTitle:'Tattoos · Paris',eyebrow:'Hand-drawn tattoos · Paris',heroTitle:'Tattoos\nwith soul.',heroIntro:'Original flash designs and custom pieces drawn by hand.',instagramUrl:'#',tallyUrl:'#',bookingUrl:'#',depositUrl:'#',email:'hello@example.com',footerRight:'Paris · tattoos by appointment',flashHeading:'Available flashes',flashIntro:'Choose a design, select a size, then book a date.',customHeading:'Have something else in mind?',customText:'Custom projects are welcome.',infoHeading:'Simple, on purpose.',infoText:'A deposit is required to secure every appointment.'};
const FALLBACK_FLASHES={items:[]};
async function getJSON(path,fallback){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error();return await r.json()}catch(e){return fallback}}
let SITE=FALLBACK_SITE, FLASHES=[];
const $=s=>document.querySelector(s);
function money(n){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n)}
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function applySite(){document.title=`${SITE.brand} — ${SITE.pageTitle}`;$('#brandTop').textContent=SITE.brand;$('#brandModal').textContent=SITE.brand;$('#heroEyebrow').textContent=SITE.eyebrow;$('#heroTitle').innerHTML=escapeHTML(SITE.heroTitle).replace(/\n/g,'<br>');$('#heroIntro').textContent=SITE.heroIntro;$('#flashHeading').textContent=SITE.flashHeading;$('#flashIntro').textContent=SITE.flashIntro;$('#customHeading').textContent=SITE.customHeading;$('#customText').textContent=SITE.customText;$('#infoHeading').textContent=SITE.infoHeading;$('#infoText').textContent=SITE.infoText;$('#instagramLink').href=SITE.instagramUrl;$('#tallyLink').href=SITE.tallyUrl;$('#emailLink').href=`mailto:${SITE.email}`;$('#footerLeft').textContent=`© ${new Date().getFullYear()} ${SITE.brand}`;$('#footerRight').textContent=SITE.footerRight}
let current='All',activeFlash=null,selectedSize=0;
function visibleFlashes(){return FLASHES.filter(f=>!String(f.status).toLowerCase().includes('hidden'))}
function categories(){return ['All',...new Set(visibleFlashes().map(f=>f.category).filter(Boolean))]}
function renderFilters(){const el=$('#filters');el.innerHTML=categories().map(c=>`<button class="filter ${c===current?'active':''}" data-cat="${escapeHTML(c)}">${escapeHTML(c)}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{current=b.dataset.cat;renderFilters();renderGrid()})}
function fromPrice(f){const prices=(f.sizes||[]).map(s=>Number(s.price)).filter(Number.isFinite);return prices.length?Math.min(...prices):0}
function renderGrid(){const el=$('#grid');const list=current==='All'?visibleFlashes():visibleFlashes().filter(f=>f.category===current);el.innerHTML=list.map(f=>`<article class="flash" data-id="${escapeHTML(f.id)}"><div class="flash-image"><img src="${escapeHTML(f.image)}" alt="${escapeHTML(f.title)}" loading="lazy"></div><div class="flash-meta"><div><div class="flash-title">${escapeHTML(f.title)}</div><div class="flash-sub">${escapeHTML(f.id)} · ${escapeHTML(f.category)} · ${escapeHTML(f.status)}</div></div><div class="price">from ${money(fromPrice(f))}</div></div></article>`).join('');el.querySelectorAll('.flash').forEach(card=>card.onclick=()=>openFlash(card.dataset.id))}
function renderSizes(){const el=$('#sizes');el.innerHTML=(activeFlash.sizes||[]).map((s,i)=>`<div class="size-row ${i===selectedSize?'selected':''}" data-i="${i}"><span>${escapeHTML(s.label)}</span><span>${money(Number(s.price))}</span></div>`).join('');el.querySelectorAll('.size-row').forEach(r=>r.onclick=()=>{selectedSize=Number(r.dataset.i);renderSizes()})}
function openFlash(id){activeFlash=FLASHES.find(f=>String(f.id)===String(id));if(!activeFlash)return;selectedSize=0;$('#detailArt').innerHTML=`<img src="${escapeHTML(activeFlash.image)}" alt="${escapeHTML(activeFlash.title)}">`;$('#detailTitle').textContent=activeFlash.title;$('#detailMeta').textContent=`${activeFlash.id} · ${activeFlash.category} · ${activeFlash.status}`;$('#detailDescription').textContent=activeFlash.description||'';$('#detailNote').textContent=activeFlash.note||'Final size can be adjusted slightly depending on placement.';renderSizes();$('#modal').classList.add('open');document.body.style.overflow='hidden'}
function closeModal(){$('#modal').classList.remove('open');document.body.style.overflow=''}
function bookingLink(){let raw=SITE.bookingUrl||'#';try{const u=new URL(raw,location.href);const size=(activeFlash.sizes||[])[selectedSize];u.searchParams.set('utm_source','ninelij-site');u.searchParams.set('utm_campaign',activeFlash.id||'flash');if(size)u.searchParams.set('utm_content',`${size.label}-${size.price}`);return u.href}catch(e){return raw}}
async function init(){[SITE,{items:FLASHES}]=await Promise.all([getJSON('data/site.json',FALLBACK_SITE),getJSON('data/flashes.json',FALLBACK_FLASHES)]);FLASHES=FLASHES||[];applySite();renderFilters();renderGrid();$('#close').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('#bookBtn').onclick=()=>{if(!activeFlash)return;window.open(bookingLink(),'_blank','noopener')}}
init();
